### ISSUE TITLE
User Interface

### ISSUE THREAD

**Issue by dealproc** [YoloDev/YOBAO#6]
Something we're going to need to discuss at some point is the user interface.  We have two basic options for this:
1. Http "Forms"
2. SPA Admin app

If we do the SPA Admin app, we can possibly create a richer UI experience vs. just the forms.

**Comment by Alxandr** [comment]
SPA that this. #yolo

Go crazy, use Polymer or Angular 2.0 ^^ (Polymer is prolly more stable, and I think it would be a good fit for stuff like this).

**Comment by ctolkien** [comment]
Need to consider what browsers to hit - but I suspect that we can probably go all latest + IE10? Maybe don't even need IE10.

**Comment by Alxandr** [comment]
Polymer is IE10+. No clue about Angular 2.0

**Comment by dealproc** [comment]
Discussions on JabbR, we decided that the first run will be full form posts... v2 would allow us to create an angular app or similar to handle this.
